### PR TITLE
Added Date/Time Picker for edit shifts view

### PR DESCRIPTION
**Pull request by sreejakshetty**
#77

screenshot from 2016-06-09 09 03 34

### CODE REVIEW

**Comment by sreejakshetty** [comment]
#77  tested on online server .

**Comment by hpdang** [comment]
once I created shifts on your online server. The shifts do not show up on the shift table. Therefore I can't check the edit shift function. Did you find the solution for that issue?

**Comment by sreejakshetty** [comment]
I am able to view it , after  unchecking the use new style option . Can you please check it now 
screenshot from 2016-06-10 22 25 27

**Comment by sreejakshetty** [comment]
@hpdang I will fix the issue why we are not able to view the shifts in map form ( new style option ).
Thanks

**Comment by sreejakshetty** [comment]
Fixed #106 here

**Pull request closed without merging**
