### PR TITLE
Ui/UX Register Page View

### PR DESCRIPTION
**Pull request by sreejakshetty**
#54

screenshot from 2016-06-06 18 19 58
screenshot from 2016-06-06 18 19 30

### CODE REVIEW

**Comment by sreejakshetty** [comment]
#54 Tested on online server

**Comment by hpdang** [comment]
All the required fields should be listed on top. You set the background in Black? It is a bit hard to see. User is not able to change that right? 

Also I wonder if the user-admin can edit the form so it fits into different events or at least the ability to edit the welcome message on the top  'By completing this form you're registering as a Chaos-Angel. This script will create you an account in the angel task sheduler.'

**Comment by sreejakshetty** [comment]
I will move all required fields to top.I didn't set the background as Black .It is default .User need to register before he can change the background/theme.We can add the option for guests also to change the background colour. should we add two themes light and dark ?

Presently , for the welcome message we need to change it in the code .Shall I change the welcome message to " 'By completing this form you're registering as a Chaos-Angel. This script will create you an account in the angel task scheduler."

**Comment by sreejakshetty** [comment]
#74 #75 I have created both the issues to add the required features/options.

**Comment by sreejakshetty** [comment]
screenshot from 2016-06-07 21 49 21
screenshot from 2016-06-07 21 49 06
screenshot from 2016-06-07 21 48 53
#74 #69

**Comment by sreejakshetty** [comment]
Moved the required fields to top of the page

**Comment by hpdang** [comment]
Hi, where did you test? this one didn't give me the same result. http://107.170.88.225/engelsystem/public/?p=register

screenshot from 2016-06-08 08 26 07

**Comment by sreejakshetty** [comment]
Please , check it now . tested on online server http://107.170.88.225/engelsystem/public/?p=register
Thank you

**Comment by sreejakshetty** [comment]
@hpdang , can we merge it . I will be adding more features to the files once it gets merged to avoid conflicts .
Thank you

**Pull request merged**
