### PR TITLE
Changed the content from german to english 

### PR DESCRIPTION
**Pull request by sreejakshetty**
#36

screenshot from 2016-05-28 12 34 53
screenshot from 2016-05-28 12 34 21

### CODE REVIEW

**Comment by hpdang** [comment]
please check!

**Comment by sreejakshetty** [comment]
@hpdang 
I will create another PR . Thank you.Understood the conflicts.

**Comment by sreejakshetty** [comment]
#38 Fixed here

**Comment by sreejakshetty** [comment]
I am closing the PR has it is already fixed #38 here .

**Pull request closed without merging**
