### PR TITLE
MVC implementation questions, settings, shifts

### PR DESCRIPTION
**Pull request by DishantK1807**

### CODE REVIEW

**Comment by mariobehling** [comment]
@kamishettysreeja25 Do these changes go inline with your implementations? Then please merge.

@DishantK1807 

> Codacy was unable to analyse your commit.

But I see there were some tests before. Any ideas?

**Comment by sreejakshetty** [comment]
@mariobehling I will check and merge it.
Thank you

**Comment by DishantK1807** [comment]
@mariobehling: For analyzing PRs from fork repositories Codacy takes some time to review it. I've set the time to minimum i.e 1hr. When we make any changes in the PR, it'll be analyzed after 1 hr of making that change. Sometime Codacy is unable to analyze the commit due to some internal problem. Then it'll analyze it after 24hrs. Just like now. Codacy has analyzed the commit and this PR has passed the check.

For PRs from same repository, Codacy will analyze the commit immediately.

**Comment by mariobehling** [comment]
Ok, thanks for the info. We don't really have this issue in the other projects. I wonder what is the difference in configuration. Cheers.

**Comment by sreejakshetty** [comment]
@mariobehling It is not working. The page is not getting loaded. I have checked the MVC-implementation branch

**Comment by mariobehling** [comment]
Ok, so I am reverting this then. @DishantK1807 Please check with @kamishettysreeja25

**Comment by DishantK1807** [comment]
@mariobehling: There is no such configuration file for Codacy. It automatically configures the project. I'll check with sreeja.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: What do you think the problem might be? I extracted the sql queries from the code the same way you did. I just didn't changed the names in install.sql file. But I changed the links to the mew file locations.

**Comment by sreejakshetty** [comment]
> @kamishettysreeja25: What do you think the problem might be? I extracted the sql queries from the code the same way you did. I just didn't changed the names in install.sql file. But I changed the links to the mew file locations.

@DishantK1807 
Before adding files, we need to sync our local repo with the development branch and then push the local changes. Please pull the changes in our terminal and push your local changes to the repo.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: I'll do that. Thank you

**Pull request merged**
