### PR TITLE
User groups

### PR DESCRIPTION
**Pull request by DishantK1807**
Created a new create groups page under admin menu:
Creating new group 
screenshot from 2016-07-28 00_08_36

Group successfully created
screenshot from 2016-07-28 00_08_45

Group displayed in Grouprights
screenshot from 2016-07-28 00_09_00

Tested on local and online server
#199 #22

### CODE REVIEW

**Comment by mariobehling** [comment]
Which issue is that? Each PR should be matched with an issue. So, we all know where to get background info and can follow up.

**Comment by DishantK1807** [comment]
#199 #22

**Comment by DishantK1807** [comment]
#201

**Comment by DishantK1807** [comment]
@mariobehling: Can we merge this PR?

**Comment by mariobehling** [comment]
@DishantK1807 There are merge conflicts now. Please resolve. Thank you.

**Comment by DishantK1807** [comment]
@mariobehling: Resolved the conflicts now. We can merge this PR.

**Comment by sreejakshetty** [comment]
@DishantK1807 
Now instead of creating a new model file for admin_cgroup_model.php we can insert the sql queries in the respective table model files.
I have moved the sql queries to respective model file. We have model files for Groups_model.php and GroupPrivileges_model.php which contains queries related to Groups table and GroupPrivileges table. Initially msquare created model files for each table in the database. This will reduce duplication of code.
Thank you.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: This PR was created before the refactoring of code was done and we cannot wait to work due to one issue. I'll add the sql queries to the groups_model.php now. Thank you.

**Comment by DishantK1807** [comment]
@mariobehling: can we merge this PR now?

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
