### PR TITLE
Updated Travis for setting database

### PR DESCRIPTION
**Pull request by DishantK1807**
Updated the Travis file for setting up the database, Now Travis ca run our tests

### CODE REVIEW

**Comment by DishantK1807** [comment]
#215 #191

**Comment by DishantK1807** [comment]
@mariobehling @hongquan: Travis passed the configuration. We can merge this PR. 
And Travis will be able to run our tests for the system

**Comment by hongquan** [comment]
@DishantK1807 For importing SQL file, this way is better: https://github.com/kamishettysreeja25/engelsystem/blob/development/install.sh#L43

**Comment by hongquan** [comment]
@DishantK1807 Did you really test your work? TravisCI log:

> mysqli::__construct(): (HY000/1045): Access denied for user 'username_here'@'localhost'

and

> No tests executed!

**Comment by DishantK1807** [comment]
@hongquan: I also checked that way, but I thought it would be better to make all the travis configuration in a single file. If you want I can set it into a single file

**Comment by DishantK1807** [comment]
> And Travis will be able to run our tests for the system
> @hongquan: Only database is set up in the configuration fro running the tests.

**Comment by hongquan** [comment]
> I thought it would be better to make all the travis configuration in a single file

I don't tell you to create a new file. Please notice the highlight

selection_129

Change the command to import.

> Only database is set up in the configuration fro running the tests

What do you mean? The target of this task is to configure database properly in .travis.yaml so that TravisCI can run our test.

**Comment by DishantK1807** [comment]
> I don't tell you to create a new file. Please notice the highlight

I tried that method, but the Travis build was failing

**Comment by hongquan** [comment]
> I tried that method, but the Travis build was failing

How did it say?

**Comment by DishantK1807** [comment]
https://travis-ci.org/fossasia/engelsystem/jobs/150460453

In my previous PR I tried many configurations for setting up the database.

This was the most stable one, in which the Travis build is not failing. #214

**Comment by hongquan** [comment]
It failed, not because of the method, but because of your bad command. You don't have habit to look into Travis log?

> ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'engelsystem' at line 1

Compare your command with @kamishettysreeja25's and see what is wrong.

> mysql -e engelsystem < db/install.sql -uroot;
> mysql -u root -p engelsystem < db/install.sql

**Comment by DishantK1807** [comment]
There is problem with the version with the MySQL version of travis that does not support 

> mysql -e engelsystem < db/install.sql -uroot;
> mysql -u root -p engelsystem < db/install.sql

https://docs.travis-ci.com/user/database-setup/#MySQL-5.6

**Comment by hongquan** [comment]
Not support? Are you sure? Isn't it just the matter of specifying distro by:

> dist: trusty
> sudo: required

**Comment by DishantK1807** [comment]
It gives an error.

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

https://travis-ci.org/fossasia/engelsystem/jobs/150828194

**Comment by hongquan** [comment]
I don't see how your travis file is, to be able to say any further.

**Comment by DishantK1807** [comment]
> before_install:
> mysql -u root -e "create database engelsystem;" 
> 
> before_script:
>  mysql -u root -e "use engelsystem;"
> mysql -u root -e "engelsystem < db/install.sql;"
> mysql -u root -e "engelsystem < db/install.sql;" `

**Comment by DishantK1807** [comment]
It gives an error while creating the database

**Comment by hongquan** [comment]
1. This is your travis file:

``` yaml
language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
dist: trusty
sudo: required


services:
- mysql
```

See how you setup MySQL. You are the one who gave me the link https://docs.travis-ci.com/user/database-setup/#MySQL-5.6, but why don't you follow its instruction in setting up MySQL? What is under the `sudo: required` line?

2.

> mysql -u root -e "engelsystem < db/install.sql;"

Bad command again! Why don't you test by yourself, on your local machine first? How much does it cost you to test on local first, to discover the error early and fix it before pushing to repo?

Look like you are running command blindly, without even care what its options ("-e") mean. Please try to understand what you are writing down http://dev.mysql.com/doc/refman/5.6/en/command-line-options.html

I don't understand why I gave you the working command `mysql -u root -p engelsystem < db/install.sql`, but you still change it to `mysql -u root -e "engelsystem < db/install.sql;"`

Read more about shell operators (like `<`) here: http://unix.stackexchange.com/questions/159513/what-are-the-shells-control-and-redirection-operators

**Comment by DishantK1807** [comment]
> See how you setup MySQL. You are the one who gave me the link https://docs.travis-ci.com/user/database-setup/#MySQL-5.6, but why don't you follow its instruction in setting up MySQL? What is under the sudo: required line?

My current travis file looks like here, after some changes, 
https://github.com/DishantK1807/engelsystem/blob/Travis-setup/.travis.yml
It gives the following error.

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

I looked into resources for this error and found some links.

http://stackoverflow.com/questions/11657829/error-2002-hy000-cant-connect-to-local-mysql-server-through-socket-var-run
http://stackoverflow.com/questions/19658891/error-2002-hy000-cant-connect-to-local-mysql-server-through-socket-var-run

I tried to restart service, using
`sudo service mysql.server start` and restart(was given in the above links) but it gave an error

> mysql.server: unrecognized service

There is a problem with the connection to the server

**Comment by hongquan** [comment]
> I tried to restart service, using
> sudo service mysql.server start

Where did you get that command from? Why don't you test on your local machine first? You are polluting Git history with a lot of untested commits (https://github.com/fossasia/engelsystem/pull/214/commits)? Right in the last comment, I reminded you to test first, but you still ignore and make a crap commit like this https://github.com/fossasia/engelsystem/pull/214/commits/e8ff17f66062117e702284a9d0b6a9dcfb254f39 ?

**Comment by hongquan** [comment]
You dropped this: https://docs.travis-ci.com/user/database-setup/#MySQL

**Comment by DishantK1807** [comment]
You might have to create the myapp_test database first. Run this as part of your build script:

> before_script:
> - mysql -e 'create database myapp_test;' 

This is giving the same error.

**Comment by hongquan** [comment]
> This is giving the same error. 

What error? Log? travis file content? How many times I complaint about your lacking-of-information question?

The error "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' " has nothing to do with _database name_. It is the error occurring in the process of **connecting to MySQL server** (don't you understand the statement "Can't connect to local MySQL server")?

And do you even care my comment https://github.com/fossasia/engelsystem/pull/217#issuecomment-238749961 ?

**Comment by DishantK1807** [comment]
My Travis file.
https://github.com/DishantK1807/engelsystem/blob/Travis-setup/.travis.yml
Travis log: 
https://travis-ci.org/DishantK1807/engelsystem/builds/151125798

I also created a `database.yml` in the repo as mentioned here, https://docs.travis-ci.com/user/database-setup/#MySQL

**Comment by hongquan** [comment]
I cannot understand how you read the documentation and why you create _database.yml_. The link https://docs.travis-ci.com/user/database-setup/#MySQL points to the key idea but you ignore it and you look into somewhere else.

selection_130

**Review by bhaveshAn — APPROVED** [review]
LGTM

**Pull request merged**
