### PR TITLE
Updated for User and Admin Settings page

### PR DESCRIPTION
**Pull request by DishantK1807**
#67

### CODE REVIEW

**Comment by DishantK1807** [comment]
@hongquan : Can we merge this PR? so I could work on #89, avoiding the conflicts

**Comment by hongquan** [comment]
@DishantK1807 
Please clean all whitespace at the end of the code line. Make a commit for it.
Please also configure your editor to automatically clean all whitespace, so that it won't happen in the future.

**Comment by vuhung** [comment]
​- We should have a coding convention standard
- And get it checked with travis CI.​

**Comment by DishantK1807** [comment]
@hongquan : done

**Comment by hongquan** [comment]
@vuhung I will look for some convention in PHP community. About automatic check in TravisCI, I'm not sure if we should use or not, because some violation is considered OK in some specific cases, and the check tool cannot understand that. Another issue is that the existing code of original author may have some convention violation and we cannot clean it all soon. If we let TravisCI to check, we may see a lot of "red status" while our commit is OK.

Python is the only language which has [official](https://www.python.org/dev/peps/pep-0008/) coding convention and many tools exists, but the tools still fail in some cases.

I think it is better now that our students install the check tool and integrate it to their editor/IDE to check automatically.

**Pull request merged**
