### PR TITLE
updated constraint for email

### PR DESCRIPTION
**Pull request by DishantK1807**
#46

### CODE REVIEW

**Comment by hongquan** [comment]
The User table is already created in install.sql, why update.sql create the table again? Did you try running it?

Did you test the case of quan@mail.com and Quan@mail.com? We have to make sure the _email_ column is case-insensitive.

**Comment by DishantK1807** [comment]
75767ce8-2916-11e6-9aa4-0b4101639649

@hongquan : I've tested it on the online server. As shown in the screenshot the other one is rejected.

**Comment by hongquan** [comment]
Ok. The sreenshot doesn't tell me _abcdeF@example.com_ is rejected because _abcdeF@example.com_ has existed, or because _abcdef@example.com_ has existed. That's why I have to ask you.

**Comment by hongquan** [comment]
In the commit, I only see the update in _update.sql_. I don't see any update in PHP. So which one assure that the email is tested in case-insensitive format?

**Comment by hongquan** [comment]
I tested on my local server and on _registeration-form_ branch. After I register with _quan@gmail.com_ email, I still can register with _quAn@gmail.com_. This is not expected.

**Comment by vuhung** [comment]
Need to know about regular expression, for email adress in this case.

No excuse for being brief on mobile.

**Comment by DishantK1807** [comment]
@hongquan : @vuhung 

capture1

In the above image, I am not allowed to register as the e-mail id already exists( Red Block). The system does not allow me to register with abcDef@example.com as abcdef@example.com already exists in the database as shown in Image 2.(highlighted)

capture2

In the 2nd image, it shows the database table, which shows that the email ID I am using to register in image 1 , already exists and the case is different.

I'll be updating the error message displayed, to tell be user Email ID already exists and in a specific case.

**Comment by DishantK1807** [comment]
@hongquan : @vuhung  Updated the error message in the PHP code using the regular expression. Now only lower case email id's will be accepted and duplicate emails will not be allowed. 

Kindly review the code.

Tested on the online server : [http://stanfordswi.info/engelsystem/public/](url)

capture3

capture4

**Comment by vuhung** [comment]
Look like we need some knowledge on database design,  not only regex.

No excuse for being brief on mobile.

**Comment by DishantK1807** [comment]
@vuhung: for the database design , the email field in the "User" is updated to be UNIQUE, and is not set BOOLEAN, so that it is case insensitive.

Updating the regex in the PHP code allows only lowercase input now.

**Comment by hongquan** [comment]
Tested on your online server, looks OK.

On my local server, there is an issue that even when all MySQL calls failed, the registration process is still successfully. But no user is inserted to database.

However, that is different issue and this PR can be merged.

**Pull request merged**
