### PR TITLE
Added Create Events Page

### PR DESCRIPTION
**Pull request by DishantK1807**

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide link to issue, description and screenshot.

**Comment by DishantK1807** [comment]
Filling information for creating events
event1

Event created Successfully
event created successfully

Creating new rooms
creating room

Room with list of events to be selected in the dropdown menu
rooms with events

Room saved 
FOSSASIA 
EVENT name - SEMINAR
room saved

**Comment by DishantK1807** [comment]
@mariobehling: Uploaded the screenshots. Please review

**Comment by DishantK1807** [comment]
@mariobehling: can we merge this PR?

**Pull request merged**
