### PR TITLE
Travis CI : updated .travis.yml #6 

### PR DESCRIPTION
**Pull request by sreejakshetty**

### CODE REVIEW

**Comment by mariobehling** [comment]
@kamishettysreeja25 Please reference the issue you are solving here.

**Comment by sreejakshetty** [comment]
screenshot from 2016-05-19 09 08 14
screenshot from 2016-05-19 12 36 47
My commits even contain Localization code for hindi language This is the screenshot which shows how it looks after integrating with the system.

**Comment by mariobehling** [comment]
@kamishettysreeja25 Please reference the issue you are solving here. Which issue is this related to? Please post screenshots in issues before making a pull requests.

Right now build is failing. Please resolve it.

**Comment by hongquan** [comment]
Hi @kamishettysreeja25 

I will close this PR, without merging, because it includes 2 features:
- Unittest
- Hindi language.

You need to make separate PR for each of them.

**Pull request closed without merging**
