### PR TITLE
Updated `Users` Table : Language as profile attributes 

### PR DESCRIPTION
**Pull request by DishantK1807**
added native_language and other_language as fields in the Database
#102 #103

### CODE REVIEW

**Comment by DishantK1807** [comment]
@hongquan : can we merge this PR ?

**Comment by hongquan** [comment]
The column name is _other_languages_, look like you will store "many languages", but why is there only 1 column for it? Are you storing many languages to 1 column? How is the data for both column? You will store full name like "English", "Hindi" or something else?

**Comment by DishantK1807** [comment]
@hongquan : In the column  `other_languages` I'll storing many languages, each separated by a comma. These languages will only be displayed on the users page.

**Comment by hongquan** [comment]
How is about the question

> How is the data for both column?

How many languages to be saved in `other_languages`? Is VARCHAR(255) enough?

**Comment by hongquan** [comment]
Why is the title "Updated `Users` Table" so generic (again)? If in the future, you want to update something in User table, and you again name it "Update `Users` Table", we will have ten R with the same name "Updated `Users` Table"?

**Comment by DishantK1807** [comment]
@hongquan : 

> How many languages to be saved in other_languages? Is VARCHAR(255) enough?

I assumed each language to be average of 10 characters, so by that assumption other_languages can store almost 20-22 languages names(including comma and spaces). I thought that would be enough for storing _other_languages_ . We can increase the size if you want.

`other_languages` will store values as:
" English, Hindi, French, German"

capture

and will be displayed as shown above

**Comment by hongquan** [comment]
- We should have a limit on how many languages can be stored. If we don't want to limit, we have to find new way of storing to database.
- I feel not good when we store full english name like "French", "Hindi" to database. ISO code (fr, hi) is better. With this, VARCHAR(2) or VARCHAR(5) is enough for `native_language`. It will also help if you want to be more specific about dialect in the future, for example, "en_GB" for British English.

**Comment by DishantK1807** [comment]
@hongquan : 

> I feel not good when we store full english name like "French", "Hindi" to database. ISO code (fr, hi) is better. With this, VARCHAR(2) or VARCHAR(5) is enough for native_language. It will also help if you want to be more specific about dialect in the future, for example, "en_GB" for British English.

That would create some problems with the user who might not be knowing the ISO codes for languages. I will change the size of _native_language_ to some lower value as you suggest. 
But I suggest we should store full name's to help every user understand it. Not every user who knows Irish language knows that `ga_IE` is it's ISO code.

**Comment by hongquan** [comment]
ISO code is what we store in database, not what we display to user, and not what is input by user. ISO code is standardized, so there are many libraries to convert it from the code to the full name (`hi` -> `Hindi`). Some libraries can even convert to name in native language, for example, `fr` to `Français`.
We also don't let user type "English" to the field. What if user types "english" or "EngIish" (I instead of L)? We only provide a drop down list and let user pick some of them. The downdown list shows the full name to user, but the real value to submit by the form is the ISO code.

**Comment by DishantK1807** [comment]
@hongquan : for storing ISO codes in the database, can we set `native_language` as VARCHAR(5) and `other_language` to VARCHAR(60) to add 10 languages [six characters for each language, 5 for ISO code and 1 for comma] . I guess 10 languages will be enough as other languages. Will display an error if the user adds more than 10 languages.

**Comment by hongquan** [comment]
I'm even stingier than you. I think 3-4 "other languages" is enough. Haha. However, I don't object if you let user have 10 "other languages".

**Comment by mariobehling** [comment]
@DishantK1807 Please resolve conflicts.

**Comment by DishantK1807** [comment]
I'll be working on this issue later. The variables defined needs to be changed

**Pull request closed without merging**
