### PR TITLE
Added Batch deleting of shifts

### PR DESCRIPTION
**Pull request by DishantK1807**

### CODE REVIEW

**Comment by DishantK1807** [comment]
#14 #118 #113

**Comment by DishantK1807** [comment]
Tested on local and online server

**Comment by hpdang** [comment]
can you provide some screenshots here please?

**Comment by DishantK1807** [comment]
batch_delete_old

Batch delete in old view. Selecting checkboxes and clicking on the delete button, deletes the selected shifts.
batch_delete_new
Batch delete in new view. Selecting checkboxes and clicking on the delete button, deletes the selected shifts.

**Comment by DishantK1807** [comment]
@hpdang : 
before
Selecting shifts to be deleted and clicking on the delete button

after

Selected shifts are deleted on clicking the delete button

**Comment by hpdang** [comment]
could you update your test server if there is any changes? https://titanpad.com/GSoC16EngelSystem. Below was the result I found when click on Shift. 
screen shot 2016-06-23 at 8 05 40 pm

**Comment by DishantK1807** [comment]
@hpdang: I made some error in my online server, now on clicking on Shifts tab it is redirecting to user's info.I am trying to figure out the problem and resolve this issue. Till then can @kamishettysreeja25 test this code her online server, so that no time is wasted and you can check this feature. The screenshots that I've provided are from my Local Server and this feature works fine on the online server. Please allow for this time to test it on @kamishettysreeja25 online server. 
@kamishettysreeja25 : Please can you test this PR on your server for this time, so that no time is wasted?

**Comment by sreejakshetty** [comment]
@DishantK1807  
screenshot from 2016-06-24 13 03 34
Initally I was able to view the shifts but after I have updated the files to the changes you have made. I am unable to view shifts.
shifts page looks something like this after I runned your code.
screenshot from 2016-06-24 13 01 29

**Comment by DishantK1807** [comment]
@kamishettysreeja25 : did you applied the code from here first #109 ? if no, then please change 1-> Y in these lines please.
`$rooms = sql_select("SELECT * FROM`Room`WHERE`show`='1' ORDER BY`Name`");`
and 
`$rooms = sql_select("SELECT`RID`AS`id`,`Name`AS`name`FROM`Room`WHERE`show`='1' ORDER BY`Name`");` 
It will work.
We can have this conversation on private messages.

**Pull request merged**
