### PR TITLE
Feature Request : Admin : Shifts : Editing existing shift 

### PR DESCRIPTION
**Pull request by sreejakshetty**
#15

### CODE REVIEW

**Comment by sreejakshetty** [comment]
screenshot from 2016-06-18 09 18 45
Once **we press the edit button** . admin is redirected to edit/create shifts page.
screenshot from 2016-06-18 08 58 48
This is the edit/create shift page where we can **update the shifts or create a new shift from the existing shift.**
After **pressing create shifts** , the page is directed to preview page where we can recheck the shifts details
screenshot from 2016-06-18 08 59 12
Once we **press save** the shift is saved and page is redirected to shifts page where we can view the shifts
screenshot from 2016-06-18 08 59 40

**Comment by sreejakshetty** [comment]
#15  tested on online server

**Comment by hpdang** [comment]
good job! Love this function.

**Comment by sreejakshetty** [comment]
Thank you :)

**Pull request merged**
