### PR TITLE
Mvc implementation user questions, settings, shifts

### PR DESCRIPTION
**Pull request by DishantK1807**

### CODE REVIEW

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Please check now. I pulled the changes from fossasia developement. This is working fine on my local server

**Comment by DishantK1807** [comment]
If this works fine. I'll add the changes that I made in shifts_controller and shifts_model.

**Comment by sreejakshetty** [comment]
screenshot from 2016-07-25 07 41 35
I am unable to view the pages.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Is the development branch from fossasia working in your localsystem?

**Comment by DishantK1807** [comment]
@kamishettysreeja25: The problem is in fossasia/development. The pages in the fossasia development are not being loaded.

**Comment by sreejakshetty** [comment]
@DishantK1807 Yes, The pages are not getting loaded. You said you have forgot some file in your previous PR. Can you tell me what file did you miss in the previous PR?

**Comment by DishantK1807** [comment]
@kamishettysreeja25: I missed `engelsystem_provider.php` which I included in this PR with all the changes. Some changes are also made to `index.php`

**Comment by sreejakshetty** [comment]
@DishantK1807 Can you share the file I will check in my localsystem.

**Comment by DishantK1807** [comment]
Those are in this PR.
https://github.com/fossasia/engelsystem/pull/189/commits/57978bc98e8c76f6fd225c93ad033d1b917a18b1

**Comment by sreejakshetty** [comment]
Integrated the  changes in #192 . Fixed the error in this PR. This PR can be closed.

**Pull request closed without merging**
