### PR TITLE
Implement MVC controller files

### PR DESCRIPTION
**Pull request by DishantK1807**
Created controller files for:
- guest_start
- guest_stats
- user_atom
- user_ical
- user_messages
- user_myshifts
- user_news
- user_questions
- user_settings
- user_shifts
#173 #174 #175

### CODE REVIEW

**Comment by mariobehling** [comment]
I am confused why there are no circle-ci and codacy tests here performed.
@DishantK1807 @kamishettysreeja25 Any ideas?

**Comment by DishantK1807** [comment]
@mariobehling: Codacy test passed.

**Comment by mariobehling** [comment]
Ok, great. What about codeclimate?

**Comment by mariobehling** [comment]
and ci/circleci ?

**Comment by DishantK1807** [comment]
Codeclimate default branch is `master`. Does not have access to change it. Looking for Cirlce-CI

**Comment by mariobehling** [comment]
@DishantK1807 Each branch should have its own test implementation. Please research about gitattribute, which might be able to help to distinguish the tests implementation when merging dev and master.

**Comment by DishantK1807** [comment]
Completed #173

**Comment by mariobehling** [comment]
Codecove and Codeclimate not running tests. Please check.

**Comment by DishantK1807** [comment]
Working on it.

**Comment by DishantK1807** [comment]
closing this PR. Will create new PR to find the error in the code

**Pull request closed without merging**
