### PR TITLE
Added Email and mobile Fields to All Angel List View

### PR DESCRIPTION
**Pull request by sreejakshetty**
#11

screenshot from 2016-05-28 13 18 27

### CODE REVIEW

**Comment by hpdang** [comment]
hi Sreeja,

i tried to test on the system you provided. I didn't see added Mobile Field under All Engels tab. 

http://107.170.29.227/engelsystem/public/
username : admin
password : gsoc_foss

hp

**Comment by sreejakshetty** [comment]
@hpdang 
Please check the changes and features  on the  following address.
new address  : http://107.170.88.225/engelsystem/public 
username : admin
password : gsoc_foss

**Comment by hpdang** [comment]
good job!

**Comment by sreejakshetty** [comment]
#36 
This issue also is solved here . so we can close the issue and PR associated with that issue.

**Pull request merged**
