### PR TITLE
Added Feature : User can send messages to members of group or angeltype

### PR DESCRIPTION
**Pull request by sreejakshetty**
#13

### CODE REVIEW

**Comment by sreejakshetty** [comment]
screenshot from 2016-06-22 10 41 30
Added **all the groups and angeltypes** to the list of recepients
screenshot from 2016-06-22 10 41 51
Now admin has **selected AngelType tester** . Now the message will be send to all the members of tester.
screenshot from 2016-06-22 10 42 05
As **sreeja is only the member of tester** . Message is send to sreeja as we can see above.

**Comment by sreejakshetty** [comment]
#13 
Tested on online server .

**Comment by hpdang** [comment]
Sreeja, how did you test? I didn't see so many test users in your system. And how did you define groups?

**Comment by sreejakshetty** [comment]
@hpdang 
groups are which are under Groups Table . Messages can be send to all the members of groups and angeltype.
screenshot from 2016-06-22 11 26 00
I have created 3 users on local server and tested it and on online server using 1 user . I will add more users.
screenshot from 2016-06-22 11 30 28

**Comment by sreejakshetty** [comment]
we can see **all the users under angeltypes** . For eg tester engeltype has following users
screenshot from 2016-06-22 12 02 53
**when admin send message to testers** by selecting the recipients as tester 
screenshot from 2016-06-22 12 03 39
Then it is send to all the **users registered for tester**.
screenshot from 2016-06-22 12 03 22

**Pull request merged**
