### PR TITLE
Mvc implement

### PR DESCRIPTION
**Pull request by DishantK1807**
Implemented MVC for:
- Shifts_controller.php
- Users_controller.php
#190

### CODE REVIEW

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Please review the changes of they go inline if your code. Pulled the changes from the `fossasia/development`  and tested in the local server.

**Comment by sreejakshetty** [comment]
@DishantK1807 Please include user_shifts as you have created a PR before. If there is an error we can work together and fix it.  All the issues of Implementing MVC model will be finished. https://github.com/fossasia/engelsystem/issues/163 https://github.com/fossasia/engelsystem/issues/186 . 
Thank you

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Pushed the code.

**Comment by sreejakshetty** [comment]
@DishantK1807 I am unable to view the pages. There may be duplicate function names.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Reverted the changes. Can we merge this PR now?

**Comment by sreejakshetty** [comment]
Tested the changes. Merging the PR.

**Pull request merged**
