### PR TITLE
Implement MVC model for admin arrive, active, export #168 

### PR DESCRIPTION
**Pull request by sreejakshetty**
Added model files, removed sql queries from controller files.
#168

### CODE REVIEW

**Comment by sreejakshetty** [comment]
@mariobehling Can we merge this PR? 
When we make a PR from development branch to master codacy errors will be shown if they exists. Codacy is not working for this PR.

**Comment by mariobehling** [comment]
Ok, so we have two options: A) Either we solve the codacy error for this commit and the reason it is not showing up at other commits or B) we just proceed anyways.

Don't you think we should solve issues when they come up?

@DishantK1807 There was a question yesterday asking for help. What is the progress here?

**Comment by sreejakshetty** [comment]
Completed #169

**Comment by mariobehling** [comment]
Ok, so I added write access to @DishantK1807 again. We need to look out for a solution that is independent from single contributors later.

**Comment by mariobehling** [comment]
@kamishettysreeja25 Checks are finished, but codacy does not show up. Please check. It does not make sense to have again potentially hundreds of codacy issues when merging to master.

**Comment by sreejakshetty** [comment]
@mariobehling Yes, I agree with you. We will wait till codacy is setup. Till then I will push my commits to local development branch.

**Comment by DishantK1807** [comment]
@mariobehling: I'll research more about a permanent solution to this problem.

**Comment by DishantK1807** [comment]
@kamishettysreeja25: Codacy now integrated to this PR. Please check those errors.

**Comment by mariobehling** [comment]
Travis failing, Circle-CI, Codeclimate not testing. Please check.

**Comment by sreejakshetty** [comment]
@mariobehling Yes, I'm checking them. Thank you.

**Comment by sreejakshetty** [comment]
@mariobehling I have integrated circle ci. All the tests pass. Please merge the PR.

**Comment by sreejakshetty** [comment]
#168 #169 #170 
All the issues are completed

**Comment by mariobehling** [comment]
Good job!

**Pull request merged**
